name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: opticut-env
        environment-file: environment.yml
        auto-activate-base: false
        miniforge-version: latest
        use-mamba: true

    - name: Install dependencies and OptiCut
      shell: bash -l {0}
      run: |
        chmod +x install_opticut.sh
        ./install_opticut.sh

    - name: Run automated tests
      shell: bash -l {0}
      run: |
        pytest tests/

